// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldKind, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldOwnerUserID, v))
}

// OrgID applies equality check predicate on the "org_id" field. It's identical to OrgIDEQ.
func OrgID(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldOrgID, v))
}

// InstanceID applies equality check predicate on the "instance_id" field. It's identical to InstanceIDEQ.
func InstanceID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldInstanceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldStatus, v))
}

// RedirectURIOrigin applies equality check predicate on the "redirect_uri_origin" field. It's identical to RedirectURIOriginEQ.
func RedirectURIOrigin(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRedirectURIOrigin, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldKind, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldName, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldOwnerUserID, v))
}

// OrgIDEQ applies the EQ predicate on the "org_id" field.
func OrgIDEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldOrgID, v))
}

// OrgIDNEQ applies the NEQ predicate on the "org_id" field.
func OrgIDNEQ(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldOrgID, v))
}

// OrgIDIn applies the In predicate on the "org_id" field.
func OrgIDIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldOrgID, vs...))
}

// OrgIDNotIn applies the NotIn predicate on the "org_id" field.
func OrgIDNotIn(vs ...int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldOrgID, vs...))
}

// OrgIDGT applies the GT predicate on the "org_id" field.
func OrgIDGT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldOrgID, v))
}

// OrgIDGTE applies the GTE predicate on the "org_id" field.
func OrgIDGTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldOrgID, v))
}

// OrgIDLT applies the LT predicate on the "org_id" field.
func OrgIDLT(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldOrgID, v))
}

// OrgIDLTE applies the LTE predicate on the "org_id" field.
func OrgIDLTE(v int64) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldOrgID, v))
}

// InstanceIDEQ applies the EQ predicate on the "instance_id" field.
func InstanceIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldInstanceID, v))
}

// InstanceIDNEQ applies the NEQ predicate on the "instance_id" field.
func InstanceIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldInstanceID, v))
}

// InstanceIDIn applies the In predicate on the "instance_id" field.
func InstanceIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldInstanceID, vs...))
}

// InstanceIDNotIn applies the NotIn predicate on the "instance_id" field.
func InstanceIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldInstanceID, vs...))
}

// InstanceIDGT applies the GT predicate on the "instance_id" field.
func InstanceIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldInstanceID, v))
}

// InstanceIDGTE applies the GTE predicate on the "instance_id" field.
func InstanceIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldInstanceID, v))
}

// InstanceIDLT applies the LT predicate on the "instance_id" field.
func InstanceIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldInstanceID, v))
}

// InstanceIDLTE applies the LTE predicate on the "instance_id" field.
func InstanceIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldInstanceID, v))
}

// InstanceIDContains applies the Contains predicate on the "instance_id" field.
func InstanceIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldInstanceID, v))
}

// InstanceIDHasPrefix applies the HasPrefix predicate on the "instance_id" field.
func InstanceIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldInstanceID, v))
}

// InstanceIDHasSuffix applies the HasSuffix predicate on the "instance_id" field.
func InstanceIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldInstanceID, v))
}

// InstanceIDIsNil applies the IsNil predicate on the "instance_id" field.
func InstanceIDIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldInstanceID))
}

// InstanceIDNotNil applies the NotNil predicate on the "instance_id" field.
func InstanceIDNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldInstanceID))
}

// InstanceIDEqualFold applies the EqualFold predicate on the "instance_id" field.
func InstanceIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldInstanceID, v))
}

// InstanceIDContainsFold applies the ContainsFold predicate on the "instance_id" field.
func InstanceIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldInstanceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldStatus, v))
}

// RedirectURIOriginEQ applies the EQ predicate on the "redirect_uri_origin" field.
func RedirectURIOriginEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginNEQ applies the NEQ predicate on the "redirect_uri_origin" field.
func RedirectURIOriginNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginIn applies the In predicate on the "redirect_uri_origin" field.
func RedirectURIOriginIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRedirectURIOrigin, vs...))
}

// RedirectURIOriginNotIn applies the NotIn predicate on the "redirect_uri_origin" field.
func RedirectURIOriginNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRedirectURIOrigin, vs...))
}

// RedirectURIOriginGT applies the GT predicate on the "redirect_uri_origin" field.
func RedirectURIOriginGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginGTE applies the GTE predicate on the "redirect_uri_origin" field.
func RedirectURIOriginGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginLT applies the LT predicate on the "redirect_uri_origin" field.
func RedirectURIOriginLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginLTE applies the LTE predicate on the "redirect_uri_origin" field.
func RedirectURIOriginLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginContains applies the Contains predicate on the "redirect_uri_origin" field.
func RedirectURIOriginContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginHasPrefix applies the HasPrefix predicate on the "redirect_uri_origin" field.
func RedirectURIOriginHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginHasSuffix applies the HasSuffix predicate on the "redirect_uri_origin" field.
func RedirectURIOriginHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginEqualFold applies the EqualFold predicate on the "redirect_uri_origin" field.
func RedirectURIOriginEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldRedirectURIOrigin, v))
}

// RedirectURIOriginContainsFold applies the ContainsFold predicate on the "redirect_uri_origin" field.
func RedirectURIOriginContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldRedirectURIOrigin, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.NotPredicates(p))
}
