// Code generated by ent, DO NOT EDIT.

package agentcronfire

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentcronfire type in the database.
	Label = "agent_cron_fire"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAgentRowID holds the string denoting the agent_row_id field in the database.
	FieldAgentRowID = "agent_row_id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldFireAt holds the string denoting the fire_at field in the database.
	FieldFireAt = "fire_at"
	// FieldCallbackURL holds the string denoting the callback_url field in the database.
	FieldCallbackURL = "callback_url"
	// FieldDedupKey holds the string denoting the dedup_key field in the database.
	FieldDedupKey = "dedup_key"
	// FieldScheduleID holds the string denoting the schedule_id field in the database.
	FieldScheduleID = "schedule_id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// Table holds the table name of the agentcronfire in the database.
	Table = "agent_cron_fires"
)

// Columns holds all SQL columns for agentcronfire fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAgentRowID,
	FieldJobID,
	FieldFireAt,
	FieldCallbackURL,
	FieldDedupKey,
	FieldScheduleID,
	FieldState,
	FieldAttempts,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(string) error
	// CallbackURLValidator is a validator for the "callback_url" field. It is called by the builders before save.
	CallbackURLValidator func(string) error
	// DedupKeyValidator is a validator for the "dedup_key" field. It is called by the builders before save.
	DedupKeyValidator func(string) error
	// ScheduleIDValidator is a validator for the "schedule_id" field. It is called by the builders before save.
	ScheduleIDValidator func(string) error
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	LastErrorValidator func(string) error
)

// State defines the type for the "state" enum field.
type State string

// StateArmed is the default value of the State enum.
const DefaultState = StateArmed

// State values.
const (
	StateArmed     State = "armed"
	StateFired     State = "fired"
	StateCancelled State = "cancelled"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateArmed, StateFired, StateCancelled:
		return nil
	default:
		return fmt.Errorf("agentcronfire: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the AgentCronFire queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAgentRowID orders the results by the agent_row_id field.
func ByAgentRowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentRowID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByFireAt orders the results by the fire_at field.
func ByFireAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFireAt, opts...).ToFunc()
}

// ByCallbackURL orders the results by the callback_url field.
func ByCallbackURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallbackURL, opts...).ToFunc()
}

// ByDedupKey orders the results by the dedup_key field.
func ByDedupKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDedupKey, opts...).ToFunc()
}

// ByScheduleID orders the results by the schedule_id field.
func ByScheduleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}
