#!/usr/bin/env bash
# Bring up the Inferno local stack. See ../SKILL.md for why each step is shaped
# the way it is -- every workaround here exists because the obvious path fails.
set -uo pipefail

REPO="$(cd "$(dirname "$0")/../../.." && pwd)"
SCRATCH="${TMPDIR:-/tmp}/inferno-local-stack"
FRESH=0
[ "${1:-}" = "--fresh" ] && FRESH=1

mkdir -p "$SCRATCH"
cd "$REPO" || exit 1

[ -f deploy/.env ] || { echo "FAIL: deploy/.env missing (needs POSTGRES_PASSWORD)"; exit 1; }
PGPW="$(grep '^POSTGRES_PASSWORD=' deploy/.env | cut -d= -f2-)"
[ -n "$PGPW" ] || { echo "FAIL: POSTGRES_PASSWORD empty in deploy/.env"; exit 1; }

docker info >/dev/null 2>&1 || { echo "FAIL: Docker is not running"; exit 1; }

# --- 1. Postgres + Redis, with host ports the base compose deliberately omits.
cat > "$SCRATCH/ports.yml" <<'YML'
# Generated by skills/inferno-local-stack. Not part of the repo.
# The base compose keeps these internal on purpose; we need them for a
# natively-run backend.
services:
  postgres:
    ports: ["127.0.0.1:5433:5432"]
  redis:
    ports: ["127.0.0.1:6380:6379"]
YML

echo "==> starting postgres + redis"
( cd deploy && docker compose -f docker-compose.local.yml -f "$SCRATCH/ports.yml" up -d postgres redis ) >/dev/null 2>&1

echo -n "    waiting for postgres"
until docker exec sub2api-postgres pg_isready -U sub2api -d sub2api >/dev/null 2>&1; do
  echo -n "."; sleep 2
done
echo " ready"

# --- 2. Port 8080. If a HEALTHY backend already owns it, leave it alone --
#        re-running this script should not bounce a working stack. Only clear
#        the port when what is there is not answering the API (typically the
#        setup-wizard process still squatting after it wrote config.yaml).
BACKEND_UP=0
if curl -s -o /dev/null http://127.0.0.1:8080/api/v1/settings/public 2>/dev/null; then
  BACKEND_UP=1
  echo "==> backend already healthy on :8080, leaving it"
elif lsof -ti :8080 >/dev/null 2>&1; then
  echo "==> clearing a non-responsive process on :8080"
  lsof -ti :8080 | xargs kill 2>/dev/null
  sleep 2
fi

# --- 3. Backend, natively. `go run` does NOT embed the frontend; that is fine,
#        we serve the UI from Vite.
cat > "$SCRATCH/run-backend.sh" <<EOF
#!/bin/sh
cd "$REPO/backend"
export DATABASE_HOST=127.0.0.1 DATABASE_PORT=5433 DATABASE_USER=sub2api \\
       DATABASE_PASSWORD='$PGPW' DATABASE_DBNAME=sub2api DATABASE_SSLMODE=disable \\
       REDIS_HOST=127.0.0.1 REDIS_PORT=6380 \\
       SERVER_HOST=127.0.0.1 SERVER_PORT=8080 \\
       ADMIN_EMAIL=admin@sub2api.local \\
       JWT_SECRET=localverify0000000000000000000000000000000000000000000000000000 \\
       RUN_MODE=standard SETUP_MIGRATION_TIMEOUT_SECONDS=0
exec go run ./cmd/server
EOF
chmod +x "$SCRATCH/run-backend.sh"

if [ "$FRESH" = "1" ]; then
  rm -f "$REPO/backend/config.yaml"
  lsof -ti :8080 2>/dev/null | xargs kill 2>/dev/null
  BACKEND_UP=0
  sleep 2
fi

if [ "$BACKEND_UP" = "0" ]; then
  echo "==> starting backend (first run compiles Go, ~1-2 min)"
  nohup sh "$SCRATCH/run-backend.sh" > "$SCRATCH/backend.log" 2>&1 &

  echo -n "    waiting for :8080"
  for _ in $(seq 1 180); do
    curl -s -o /dev/null http://127.0.0.1:8080/setup/status 2>/dev/null && break
    echo -n "."; sleep 2
  done
  echo ""
fi

# --- 4. Setup wizard, if this is a first run. It writes config.yaml then EXITS
#        expecting a systemd restart that never comes on macOS.
if curl -s http://127.0.0.1:8080/setup/status 2>/dev/null | grep -q '"needs_setup":true'; then
  echo "==> first run: driving the setup wizard"
  python3 - "$PGPW" > "$SCRATCH/install.json" <<'PY'
import json, sys
print(json.dumps({
  "database": {"host": "127.0.0.1", "port": 5433, "user": "sub2api",
               "password": sys.argv[1], "dbname": "sub2api", "sslmode": "disable"},
  "redis":    {"host": "127.0.0.1", "port": 6380, "username": "", "password": "",
               "db": 0, "enable_tls": False},
  "admin":    {"email": "admin@sub2api.local",
               "password": "36232e0cd5be929e4004e4ca025b100e"},
  "server":   {"host": "127.0.0.1", "port": 8080, "mode": "debug"},
}))
PY
  curl -s -X POST http://127.0.0.1:8080/setup/install \
       -H 'Content-Type: application/json' -d @"$SCRATCH/install.json" >/dev/null
  sleep 5
  lsof -ti :8080 | xargs kill 2>/dev/null   # it exits, but make sure
  sleep 2
  echo "==> restarting backend after install"
  nohup sh "$SCRATCH/run-backend.sh" > "$SCRATCH/backend.log" 2>&1 &
  echo -n "    waiting for :8080"
  for _ in $(seq 1 120); do
    curl -s -o /dev/null http://127.0.0.1:8080/api/v1/settings/public 2>/dev/null && break
    echo -n "."; sleep 2
  done
  echo ""
fi

# --- 5. Vite. Serves the UI and proxies /api, /v1, /setup to :8080.
if ! curl -s -o /dev/null http://127.0.0.1:3000/ 2>/dev/null; then
  echo "==> starting vite dev server"
  ( cd "$REPO/inferno-frontend" && nohup pnpm run dev > "$SCRATCH/vite.log" 2>&1 & )
  echo -n "    waiting for :3000"
  for _ in $(seq 1 60); do
    curl -s -o /dev/null http://127.0.0.1:3000/ 2>/dev/null && break
    echo -n "."; sleep 2
  done
  echo ""
fi

cat <<EOF

  Inferno local stack is up.

    UI          http://localhost:3000      <- use this, NOT :8080
    API         http://localhost:8080/api/v1
    Postgres    127.0.0.1:5433   (docker exec sub2api-postgres psql -U sub2api -d sub2api)
    Redis       127.0.0.1:6380

    login       admin@sub2api.local / 36232e0cd5be929e4004e4ca025b100e
                two-step: type email -> Return -> CLEAR field -> type password -> Return
                then press Escape to dismiss the onboarding tour

    logs        $SCRATCH/backend.log
                $SCRATCH/vite.log

EOF
