// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agent"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdate) SetUpdatedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *AgentUpdate) SetPublicID(v string) *AgentUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillablePublicID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentUpdate) SetUserID(v int64) *AgentUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableUserID(v *int64) *AgentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AgentUpdate) AddUserID(v int64) *AgentUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *AgentUpdate) SetOrgID(v int64) *AgentUpdate {
	_u.mutation.ResetOrgID()
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableOrgID(v *int64) *AgentUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// AddOrgID adds value to the "org_id" field.
func (_u *AgentUpdate) AddOrgID(v int64) *AgentUpdate {
	_u.mutation.AddOrgID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdate) SetName(v string) *AgentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableName(v *string) *AgentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDashboardURL sets the "dashboard_url" field.
func (_u *AgentUpdate) SetDashboardURL(v string) *AgentUpdate {
	_u.mutation.SetDashboardURL(v)
	return _u
}

// SetNillableDashboardURL sets the "dashboard_url" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDashboardURL(v *string) *AgentUpdate {
	if v != nil {
		_u.SetDashboardURL(*v)
	}
	return _u
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (_u *AgentUpdate) SetOcPlatformUserID(v string) *AgentUpdate {
	_u.mutation.SetOcPlatformUserID(v)
	return _u
}

// SetNillableOcPlatformUserID sets the "oc_platform_user_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableOcPlatformUserID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetOcPlatformUserID(*v)
	}
	return _u
}

// ClearOcPlatformUserID clears the value of the "oc_platform_user_id" field.
func (_u *AgentUpdate) ClearOcPlatformUserID() *AgentUpdate {
	_u.mutation.ClearOcPlatformUserID()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AgentUpdate) SetLastSeenAt(v time.Time) *AgentUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLastSeenAt(v *time.Time) *AgentUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *AgentUpdate) ClearLastSeenAt() *AgentUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AgentUpdate) SetRevokedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableRevokedAt(v *time.Time) *AgentUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AgentUpdate) ClearRevokedAt() *AgentUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := agent.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "Agent.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DashboardURL(); ok {
		if err := agent.DashboardURLValidator(v); err != nil {
			return &ValidationError{Name: "dashboard_url", err: fmt.Errorf(`ent: validator failed for field "Agent.dashboard_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OcPlatformUserID(); ok {
		if err := agent.OcPlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "oc_platform_user_id", err: fmt.Errorf(`ent: validator failed for field "Agent.oc_platform_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(agent.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(agent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(agent.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrgID(); ok {
		_spec.AddField(agent.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DashboardURL(); ok {
		_spec.SetField(agent.FieldDashboardURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OcPlatformUserID(); ok {
		_spec.SetField(agent.FieldOcPlatformUserID, field.TypeString, value)
	}
	if _u.mutation.OcPlatformUserIDCleared() {
		_spec.ClearField(agent.FieldOcPlatformUserID, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(agent.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(agent.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(agent.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(agent.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdateOne) SetUpdatedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *AgentUpdateOne) SetPublicID(v string) *AgentUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillablePublicID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AgentUpdateOne) SetUserID(v int64) *AgentUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableUserID(v *int64) *AgentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AgentUpdateOne) AddUserID(v int64) *AgentUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *AgentUpdateOne) SetOrgID(v int64) *AgentUpdateOne {
	_u.mutation.ResetOrgID()
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableOrgID(v *int64) *AgentUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// AddOrgID adds value to the "org_id" field.
func (_u *AgentUpdateOne) AddOrgID(v int64) *AgentUpdateOne {
	_u.mutation.AddOrgID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdateOne) SetName(v string) *AgentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableName(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDashboardURL sets the "dashboard_url" field.
func (_u *AgentUpdateOne) SetDashboardURL(v string) *AgentUpdateOne {
	_u.mutation.SetDashboardURL(v)
	return _u
}

// SetNillableDashboardURL sets the "dashboard_url" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDashboardURL(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetDashboardURL(*v)
	}
	return _u
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (_u *AgentUpdateOne) SetOcPlatformUserID(v string) *AgentUpdateOne {
	_u.mutation.SetOcPlatformUserID(v)
	return _u
}

// SetNillableOcPlatformUserID sets the "oc_platform_user_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableOcPlatformUserID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetOcPlatformUserID(*v)
	}
	return _u
}

// ClearOcPlatformUserID clears the value of the "oc_platform_user_id" field.
func (_u *AgentUpdateOne) ClearOcPlatformUserID() *AgentUpdateOne {
	_u.mutation.ClearOcPlatformUserID()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AgentUpdateOne) SetLastSeenAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLastSeenAt(v *time.Time) *AgentUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *AgentUpdateOne) ClearLastSeenAt() *AgentUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AgentUpdateOne) SetRevokedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableRevokedAt(v *time.Time) *AgentUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AgentUpdateOne) ClearRevokedAt() *AgentUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := agent.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "Agent.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DashboardURL(); ok {
		if err := agent.DashboardURLValidator(v); err != nil {
			return &ValidationError{Name: "dashboard_url", err: fmt.Errorf(`ent: validator failed for field "Agent.dashboard_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OcPlatformUserID(); ok {
		if err := agent.OcPlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "oc_platform_user_id", err: fmt.Errorf(`ent: validator failed for field "Agent.oc_platform_user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(agent.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(agent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(agent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(agent.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrgID(); ok {
		_spec.AddField(agent.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DashboardURL(); ok {
		_spec.SetField(agent.FieldDashboardURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OcPlatformUserID(); ok {
		_spec.SetField(agent.FieldOcPlatformUserID, field.TypeString, value)
	}
	if _u.mutation.OcPlatformUserIDCleared() {
		_spec.ClearField(agent.FieldOcPlatformUserID, field.TypeString)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(agent.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(agent.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(agent.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(agent.FieldRevokedAt, field.TypeTime)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
