// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agent"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCreate) SetCreatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCreatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentCreate) SetUpdatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableUpdatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *AgentCreate) SetPublicID(v string) *AgentCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AgentCreate) SetUserID(v int64) *AgentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *AgentCreate) SetOrgID(v int64) *AgentCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AgentCreate) SetName(v string) *AgentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDashboardURL sets the "dashboard_url" field.
func (_c *AgentCreate) SetDashboardURL(v string) *AgentCreate {
	_c.mutation.SetDashboardURL(v)
	return _c
}

// SetNillableDashboardURL sets the "dashboard_url" field if the given value is not nil.
func (_c *AgentCreate) SetNillableDashboardURL(v *string) *AgentCreate {
	if v != nil {
		_c.SetDashboardURL(*v)
	}
	return _c
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (_c *AgentCreate) SetOcPlatformUserID(v string) *AgentCreate {
	_c.mutation.SetOcPlatformUserID(v)
	return _c
}

// SetNillableOcPlatformUserID sets the "oc_platform_user_id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableOcPlatformUserID(v *string) *AgentCreate {
	if v != nil {
		_c.SetOcPlatformUserID(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AgentCreate) SetLastSeenAt(v time.Time) *AgentCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableLastSeenAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AgentCreate) SetRevokedAt(v time.Time) *AgentCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableRevokedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the AgentMutation object of the builder.
func (_c *AgentCreate) Mutation() *AgentMutation {
	return _c.mutation
}

// Save creates the Agent in the database.
func (_c *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DashboardURL(); !ok {
		v := agent.DefaultDashboardURL
		_c.mutation.SetDashboardURL(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Agent.updated_at"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "Agent.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := agent.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "Agent.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Agent.user_id"`)}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "Agent.org_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Agent.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DashboardURL(); !ok {
		return &ValidationError{Name: "dashboard_url", err: errors.New(`ent: missing required field "Agent.dashboard_url"`)}
	}
	if v, ok := _c.mutation.DashboardURL(); ok {
		if err := agent.DashboardURLValidator(v); err != nil {
			return &ValidationError{Name: "dashboard_url", err: fmt.Errorf(`ent: validator failed for field "Agent.dashboard_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OcPlatformUserID(); ok {
		if err := agent.OcPlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "oc_platform_user_id", err: fmt.Errorf(`ent: validator failed for field "Agent.oc_platform_user_id": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(agent.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(agent.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(agent.FieldOrgID, field.TypeInt64, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DashboardURL(); ok {
		_spec.SetField(agent.FieldDashboardURL, field.TypeString, value)
		_node.DashboardURL = value
	}
	if value, ok := _c.mutation.OcPlatformUserID(); ok {
		_spec.SetField(agent.FieldOcPlatformUserID, field.TypeString, value)
		_node.OcPlatformUserID = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(agent.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(agent.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Agent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCreate) OnConflict(opts ...sql.ConflictOption) *AgentUpsertOne {
	_c.conflict = opts
	return &AgentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCreate) OnConflictColumns(columns ...string) *AgentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentUpsertOne{
		create: _c,
	}
}

type (
	// AgentUpsertOne is the builder for "upsert"-ing
	//  one Agent node.
	AgentUpsertOne struct {
		create *AgentCreate
	}

	// AgentUpsert is the "OnConflict" setter.
	AgentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsert) SetUpdatedAt(v time.Time) *AgentUpsert {
	u.Set(agent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsert) UpdateUpdatedAt() *AgentUpsert {
	u.SetExcluded(agent.FieldUpdatedAt)
	return u
}

// SetPublicID sets the "public_id" field.
func (u *AgentUpsert) SetPublicID(v string) *AgentUpsert {
	u.Set(agent.FieldPublicID, v)
	return u
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdatePublicID() *AgentUpsert {
	u.SetExcluded(agent.FieldPublicID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AgentUpsert) SetUserID(v int64) *AgentUpsert {
	u.Set(agent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateUserID() *AgentUpsert {
	u.SetExcluded(agent.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AgentUpsert) AddUserID(v int64) *AgentUpsert {
	u.Add(agent.FieldUserID, v)
	return u
}

// SetOrgID sets the "org_id" field.
func (u *AgentUpsert) SetOrgID(v int64) *AgentUpsert {
	u.Set(agent.FieldOrgID, v)
	return u
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateOrgID() *AgentUpsert {
	u.SetExcluded(agent.FieldOrgID)
	return u
}

// AddOrgID adds v to the "org_id" field.
func (u *AgentUpsert) AddOrgID(v int64) *AgentUpsert {
	u.Add(agent.FieldOrgID, v)
	return u
}

// SetName sets the "name" field.
func (u *AgentUpsert) SetName(v string) *AgentUpsert {
	u.Set(agent.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentUpsert) UpdateName() *AgentUpsert {
	u.SetExcluded(agent.FieldName)
	return u
}

// SetDashboardURL sets the "dashboard_url" field.
func (u *AgentUpsert) SetDashboardURL(v string) *AgentUpsert {
	u.Set(agent.FieldDashboardURL, v)
	return u
}

// UpdateDashboardURL sets the "dashboard_url" field to the value that was provided on create.
func (u *AgentUpsert) UpdateDashboardURL() *AgentUpsert {
	u.SetExcluded(agent.FieldDashboardURL)
	return u
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (u *AgentUpsert) SetOcPlatformUserID(v string) *AgentUpsert {
	u.Set(agent.FieldOcPlatformUserID, v)
	return u
}

// UpdateOcPlatformUserID sets the "oc_platform_user_id" field to the value that was provided on create.
func (u *AgentUpsert) UpdateOcPlatformUserID() *AgentUpsert {
	u.SetExcluded(agent.FieldOcPlatformUserID)
	return u
}

// ClearOcPlatformUserID clears the value of the "oc_platform_user_id" field.
func (u *AgentUpsert) ClearOcPlatformUserID() *AgentUpsert {
	u.SetNull(agent.FieldOcPlatformUserID)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AgentUpsert) SetLastSeenAt(v time.Time) *AgentUpsert {
	u.Set(agent.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AgentUpsert) UpdateLastSeenAt() *AgentUpsert {
	u.SetExcluded(agent.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *AgentUpsert) ClearLastSeenAt() *AgentUpsert {
	u.SetNull(agent.FieldLastSeenAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AgentUpsert) SetRevokedAt(v time.Time) *AgentUpsert {
	u.Set(agent.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AgentUpsert) UpdateRevokedAt() *AgentUpsert {
	u.SetExcluded(agent.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AgentUpsert) ClearRevokedAt() *AgentUpsert {
	u.SetNull(agent.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentUpsertOne) UpdateNewValues() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentUpsertOne) Ignore() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentUpsertOne) DoNothing() *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCreate.OnConflict
// documentation for more info.
func (u *AgentUpsertOne) Update(set func(*AgentUpsert)) *AgentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsertOne) SetUpdatedAt(v time.Time) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateUpdatedAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *AgentUpsertOne) SetPublicID(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdatePublicID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AgentUpsertOne) SetUserID(v int64) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AgentUpsertOne) AddUserID(v int64) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateUserID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUserID()
	})
}

// SetOrgID sets the "org_id" field.
func (u *AgentUpsertOne) SetOrgID(v int64) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetOrgID(v)
	})
}

// AddOrgID adds v to the "org_id" field.
func (u *AgentUpsertOne) AddOrgID(v int64) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.AddOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateOrgID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateOrgID()
	})
}

// SetName sets the "name" field.
func (u *AgentUpsertOne) SetName(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateName() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateName()
	})
}

// SetDashboardURL sets the "dashboard_url" field.
func (u *AgentUpsertOne) SetDashboardURL(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetDashboardURL(v)
	})
}

// UpdateDashboardURL sets the "dashboard_url" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateDashboardURL() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateDashboardURL()
	})
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (u *AgentUpsertOne) SetOcPlatformUserID(v string) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetOcPlatformUserID(v)
	})
}

// UpdateOcPlatformUserID sets the "oc_platform_user_id" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateOcPlatformUserID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateOcPlatformUserID()
	})
}

// ClearOcPlatformUserID clears the value of the "oc_platform_user_id" field.
func (u *AgentUpsertOne) ClearOcPlatformUserID() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearOcPlatformUserID()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AgentUpsertOne) SetLastSeenAt(v time.Time) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateLastSeenAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *AgentUpsertOne) ClearLastSeenAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AgentUpsertOne) SetRevokedAt(v time.Time) *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AgentUpsertOne) UpdateRevokedAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AgentUpsertOne) ClearRevokedAt() *AgentUpsertOne {
	return u.Update(func(s *AgentUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AgentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
	conflict []sql.ConflictOption
}

// Save creates the Agent entities in the database.
func (_c *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Agent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentUpsertBulk {
	_c.conflict = opts
	return &AgentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCreateBulk) OnConflictColumns(columns ...string) *AgentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentUpsertBulk{
		create: _c,
	}
}

// AgentUpsertBulk is the builder for "upsert"-ing
// a bulk of Agent nodes.
type AgentUpsertBulk struct {
	create *AgentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentUpsertBulk) UpdateNewValues() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Agent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentUpsertBulk) Ignore() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentUpsertBulk) DoNothing() *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCreateBulk.OnConflict
// documentation for more info.
func (u *AgentUpsertBulk) Update(set func(*AgentUpsert)) *AgentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentUpsertBulk) SetUpdatedAt(v time.Time) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateUpdatedAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublicID sets the "public_id" field.
func (u *AgentUpsertBulk) SetPublicID(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdatePublicID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdatePublicID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AgentUpsertBulk) SetUserID(v int64) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AgentUpsertBulk) AddUserID(v int64) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateUserID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateUserID()
	})
}

// SetOrgID sets the "org_id" field.
func (u *AgentUpsertBulk) SetOrgID(v int64) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetOrgID(v)
	})
}

// AddOrgID adds v to the "org_id" field.
func (u *AgentUpsertBulk) AddOrgID(v int64) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.AddOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateOrgID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateOrgID()
	})
}

// SetName sets the "name" field.
func (u *AgentUpsertBulk) SetName(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateName() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateName()
	})
}

// SetDashboardURL sets the "dashboard_url" field.
func (u *AgentUpsertBulk) SetDashboardURL(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetDashboardURL(v)
	})
}

// UpdateDashboardURL sets the "dashboard_url" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateDashboardURL() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateDashboardURL()
	})
}

// SetOcPlatformUserID sets the "oc_platform_user_id" field.
func (u *AgentUpsertBulk) SetOcPlatformUserID(v string) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetOcPlatformUserID(v)
	})
}

// UpdateOcPlatformUserID sets the "oc_platform_user_id" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateOcPlatformUserID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateOcPlatformUserID()
	})
}

// ClearOcPlatformUserID clears the value of the "oc_platform_user_id" field.
func (u *AgentUpsertBulk) ClearOcPlatformUserID() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearOcPlatformUserID()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AgentUpsertBulk) SetLastSeenAt(v time.Time) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateLastSeenAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *AgentUpsertBulk) ClearLastSeenAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AgentUpsertBulk) SetRevokedAt(v time.Time) *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AgentUpsertBulk) UpdateRevokedAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AgentUpsertBulk) ClearRevokedAt() *AgentUpsertBulk {
	return u.Update(func(s *AgentUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AgentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
