// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/agentcronfire"
)

// AgentCronFireCreate is the builder for creating a AgentCronFire entity.
type AgentCronFireCreate struct {
	config
	mutation *AgentCronFireMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCronFireCreate) SetCreatedAt(v time.Time) *AgentCronFireCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCronFireCreate) SetNillableCreatedAt(v *time.Time) *AgentCronFireCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentCronFireCreate) SetUpdatedAt(v time.Time) *AgentCronFireCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentCronFireCreate) SetNillableUpdatedAt(v *time.Time) *AgentCronFireCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAgentRowID sets the "agent_row_id" field.
func (_c *AgentCronFireCreate) SetAgentRowID(v int64) *AgentCronFireCreate {
	_c.mutation.SetAgentRowID(v)
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *AgentCronFireCreate) SetJobID(v string) *AgentCronFireCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetFireAt sets the "fire_at" field.
func (_c *AgentCronFireCreate) SetFireAt(v time.Time) *AgentCronFireCreate {
	_c.mutation.SetFireAt(v)
	return _c
}

// SetCallbackURL sets the "callback_url" field.
func (_c *AgentCronFireCreate) SetCallbackURL(v string) *AgentCronFireCreate {
	_c.mutation.SetCallbackURL(v)
	return _c
}

// SetDedupKey sets the "dedup_key" field.
func (_c *AgentCronFireCreate) SetDedupKey(v string) *AgentCronFireCreate {
	_c.mutation.SetDedupKey(v)
	return _c
}

// SetScheduleID sets the "schedule_id" field.
func (_c *AgentCronFireCreate) SetScheduleID(v string) *AgentCronFireCreate {
	_c.mutation.SetScheduleID(v)
	return _c
}

// SetState sets the "state" field.
func (_c *AgentCronFireCreate) SetState(v agentcronfire.State) *AgentCronFireCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *AgentCronFireCreate) SetNillableState(v *agentcronfire.State) *AgentCronFireCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *AgentCronFireCreate) SetAttempts(v int) *AgentCronFireCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *AgentCronFireCreate) SetNillableAttempts(v *int) *AgentCronFireCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *AgentCronFireCreate) SetLastError(v string) *AgentCronFireCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *AgentCronFireCreate) SetNillableLastError(v *string) *AgentCronFireCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// Mutation returns the AgentCronFireMutation object of the builder.
func (_c *AgentCronFireCreate) Mutation() *AgentCronFireMutation {
	return _c.mutation
}

// Save creates the AgentCronFire in the database.
func (_c *AgentCronFireCreate) Save(ctx context.Context) (*AgentCronFire, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCronFireCreate) SaveX(ctx context.Context) *AgentCronFire {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCronFireCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCronFireCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCronFireCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentcronfire.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentcronfire.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := agentcronfire.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := agentcronfire.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := agentcronfire.DefaultLastError
		_c.mutation.SetLastError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCronFireCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentCronFire.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentCronFire.updated_at"`)}
	}
	if _, ok := _c.mutation.AgentRowID(); !ok {
		return &ValidationError{Name: "agent_row_id", err: errors.New(`ent: missing required field "AgentCronFire.agent_row_id"`)}
	}
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "AgentCronFire.job_id"`)}
	}
	if v, ok := _c.mutation.JobID(); ok {
		if err := agentcronfire.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FireAt(); !ok {
		return &ValidationError{Name: "fire_at", err: errors.New(`ent: missing required field "AgentCronFire.fire_at"`)}
	}
	if _, ok := _c.mutation.CallbackURL(); !ok {
		return &ValidationError{Name: "callback_url", err: errors.New(`ent: missing required field "AgentCronFire.callback_url"`)}
	}
	if v, ok := _c.mutation.CallbackURL(); ok {
		if err := agentcronfire.CallbackURLValidator(v); err != nil {
			return &ValidationError{Name: "callback_url", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.callback_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DedupKey(); !ok {
		return &ValidationError{Name: "dedup_key", err: errors.New(`ent: missing required field "AgentCronFire.dedup_key"`)}
	}
	if v, ok := _c.mutation.DedupKey(); ok {
		if err := agentcronfire.DedupKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedup_key", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.dedup_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScheduleID(); !ok {
		return &ValidationError{Name: "schedule_id", err: errors.New(`ent: missing required field "AgentCronFire.schedule_id"`)}
	}
	if v, ok := _c.mutation.ScheduleID(); ok {
		if err := agentcronfire.ScheduleIDValidator(v); err != nil {
			return &ValidationError{Name: "schedule_id", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.schedule_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AgentCronFire.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := agentcronfire.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "AgentCronFire.attempts"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "AgentCronFire.last_error"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := agentcronfire.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "AgentCronFire.last_error": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentCronFireCreate) sqlSave(ctx context.Context) (*AgentCronFire, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCronFireCreate) createSpec() (*AgentCronFire, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentCronFire{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentcronfire.Table, sqlgraph.NewFieldSpec(agentcronfire.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentcronfire.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentcronfire.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AgentRowID(); ok {
		_spec.SetField(agentcronfire.FieldAgentRowID, field.TypeInt64, value)
		_node.AgentRowID = value
	}
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(agentcronfire.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.FireAt(); ok {
		_spec.SetField(agentcronfire.FieldFireAt, field.TypeTime, value)
		_node.FireAt = value
	}
	if value, ok := _c.mutation.CallbackURL(); ok {
		_spec.SetField(agentcronfire.FieldCallbackURL, field.TypeString, value)
		_node.CallbackURL = value
	}
	if value, ok := _c.mutation.DedupKey(); ok {
		_spec.SetField(agentcronfire.FieldDedupKey, field.TypeString, value)
		_node.DedupKey = value
	}
	if value, ok := _c.mutation.ScheduleID(); ok {
		_spec.SetField(agentcronfire.FieldScheduleID, field.TypeString, value)
		_node.ScheduleID = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(agentcronfire.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(agentcronfire.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(agentcronfire.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentCronFire.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentCronFireUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCronFireCreate) OnConflict(opts ...sql.ConflictOption) *AgentCronFireUpsertOne {
	_c.conflict = opts
	return &AgentCronFireUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCronFireCreate) OnConflictColumns(columns ...string) *AgentCronFireUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentCronFireUpsertOne{
		create: _c,
	}
}

type (
	// AgentCronFireUpsertOne is the builder for "upsert"-ing
	//  one AgentCronFire node.
	AgentCronFireUpsertOne struct {
		create *AgentCronFireCreate
	}

	// AgentCronFireUpsert is the "OnConflict" setter.
	AgentCronFireUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentCronFireUpsert) SetUpdatedAt(v time.Time) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateUpdatedAt() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldUpdatedAt)
	return u
}

// SetAgentRowID sets the "agent_row_id" field.
func (u *AgentCronFireUpsert) SetAgentRowID(v int64) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldAgentRowID, v)
	return u
}

// UpdateAgentRowID sets the "agent_row_id" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateAgentRowID() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldAgentRowID)
	return u
}

// AddAgentRowID adds v to the "agent_row_id" field.
func (u *AgentCronFireUpsert) AddAgentRowID(v int64) *AgentCronFireUpsert {
	u.Add(agentcronfire.FieldAgentRowID, v)
	return u
}

// SetJobID sets the "job_id" field.
func (u *AgentCronFireUpsert) SetJobID(v string) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateJobID() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldJobID)
	return u
}

// SetFireAt sets the "fire_at" field.
func (u *AgentCronFireUpsert) SetFireAt(v time.Time) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldFireAt, v)
	return u
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateFireAt() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldFireAt)
	return u
}

// SetCallbackURL sets the "callback_url" field.
func (u *AgentCronFireUpsert) SetCallbackURL(v string) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldCallbackURL, v)
	return u
}

// UpdateCallbackURL sets the "callback_url" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateCallbackURL() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldCallbackURL)
	return u
}

// SetDedupKey sets the "dedup_key" field.
func (u *AgentCronFireUpsert) SetDedupKey(v string) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldDedupKey, v)
	return u
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateDedupKey() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldDedupKey)
	return u
}

// SetScheduleID sets the "schedule_id" field.
func (u *AgentCronFireUpsert) SetScheduleID(v string) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldScheduleID, v)
	return u
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateScheduleID() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldScheduleID)
	return u
}

// SetState sets the "state" field.
func (u *AgentCronFireUpsert) SetState(v agentcronfire.State) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateState() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldState)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *AgentCronFireUpsert) SetAttempts(v int) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateAttempts() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *AgentCronFireUpsert) AddAttempts(v int) *AgentCronFireUpsert {
	u.Add(agentcronfire.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *AgentCronFireUpsert) SetLastError(v string) *AgentCronFireUpsert {
	u.Set(agentcronfire.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AgentCronFireUpsert) UpdateLastError() *AgentCronFireUpsert {
	u.SetExcluded(agentcronfire.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentCronFireUpsertOne) UpdateNewValues() *AgentCronFireUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(agentcronfire.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AgentCronFireUpsertOne) Ignore() *AgentCronFireUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentCronFireUpsertOne) DoNothing() *AgentCronFireUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCronFireCreate.OnConflict
// documentation for more info.
func (u *AgentCronFireUpsertOne) Update(set func(*AgentCronFireUpsert)) *AgentCronFireUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentCronFireUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentCronFireUpsertOne) SetUpdatedAt(v time.Time) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateUpdatedAt() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentRowID sets the "agent_row_id" field.
func (u *AgentCronFireUpsertOne) SetAgentRowID(v int64) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetAgentRowID(v)
	})
}

// AddAgentRowID adds v to the "agent_row_id" field.
func (u *AgentCronFireUpsertOne) AddAgentRowID(v int64) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.AddAgentRowID(v)
	})
}

// UpdateAgentRowID sets the "agent_row_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateAgentRowID() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateAgentRowID()
	})
}

// SetJobID sets the "job_id" field.
func (u *AgentCronFireUpsertOne) SetJobID(v string) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateJobID() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateJobID()
	})
}

// SetFireAt sets the "fire_at" field.
func (u *AgentCronFireUpsertOne) SetFireAt(v time.Time) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetFireAt(v)
	})
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateFireAt() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateFireAt()
	})
}

// SetCallbackURL sets the "callback_url" field.
func (u *AgentCronFireUpsertOne) SetCallbackURL(v string) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetCallbackURL(v)
	})
}

// UpdateCallbackURL sets the "callback_url" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateCallbackURL() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateCallbackURL()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *AgentCronFireUpsertOne) SetDedupKey(v string) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateDedupKey() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateDedupKey()
	})
}

// SetScheduleID sets the "schedule_id" field.
func (u *AgentCronFireUpsertOne) SetScheduleID(v string) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetScheduleID(v)
	})
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateScheduleID() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateScheduleID()
	})
}

// SetState sets the "state" field.
func (u *AgentCronFireUpsertOne) SetState(v agentcronfire.State) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateState() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateState()
	})
}

// SetAttempts sets the "attempts" field.
func (u *AgentCronFireUpsertOne) SetAttempts(v int) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *AgentCronFireUpsertOne) AddAttempts(v int) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateAttempts() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *AgentCronFireUpsertOne) SetLastError(v string) *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AgentCronFireUpsertOne) UpdateLastError() *AgentCronFireUpsertOne {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *AgentCronFireUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCronFireCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentCronFireUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AgentCronFireUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AgentCronFireUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AgentCronFireCreateBulk is the builder for creating many AgentCronFire entities in bulk.
type AgentCronFireCreateBulk struct {
	config
	err      error
	builders []*AgentCronFireCreate
	conflict []sql.ConflictOption
}

// Save creates the AgentCronFire entities in the database.
func (_c *AgentCronFireCreateBulk) Save(ctx context.Context) ([]*AgentCronFire, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentCronFire, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentCronFireMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCronFireCreateBulk) SaveX(ctx context.Context) []*AgentCronFire {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCronFireCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCronFireCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AgentCronFire.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AgentCronFireUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AgentCronFireCreateBulk) OnConflict(opts ...sql.ConflictOption) *AgentCronFireUpsertBulk {
	_c.conflict = opts
	return &AgentCronFireUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AgentCronFireCreateBulk) OnConflictColumns(columns ...string) *AgentCronFireUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AgentCronFireUpsertBulk{
		create: _c,
	}
}

// AgentCronFireUpsertBulk is the builder for "upsert"-ing
// a bulk of AgentCronFire nodes.
type AgentCronFireUpsertBulk struct {
	create *AgentCronFireCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AgentCronFireUpsertBulk) UpdateNewValues() *AgentCronFireUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(agentcronfire.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AgentCronFire.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AgentCronFireUpsertBulk) Ignore() *AgentCronFireUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AgentCronFireUpsertBulk) DoNothing() *AgentCronFireUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AgentCronFireCreateBulk.OnConflict
// documentation for more info.
func (u *AgentCronFireUpsertBulk) Update(set func(*AgentCronFireUpsert)) *AgentCronFireUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AgentCronFireUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AgentCronFireUpsertBulk) SetUpdatedAt(v time.Time) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateUpdatedAt() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentRowID sets the "agent_row_id" field.
func (u *AgentCronFireUpsertBulk) SetAgentRowID(v int64) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetAgentRowID(v)
	})
}

// AddAgentRowID adds v to the "agent_row_id" field.
func (u *AgentCronFireUpsertBulk) AddAgentRowID(v int64) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.AddAgentRowID(v)
	})
}

// UpdateAgentRowID sets the "agent_row_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateAgentRowID() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateAgentRowID()
	})
}

// SetJobID sets the "job_id" field.
func (u *AgentCronFireUpsertBulk) SetJobID(v string) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateJobID() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateJobID()
	})
}

// SetFireAt sets the "fire_at" field.
func (u *AgentCronFireUpsertBulk) SetFireAt(v time.Time) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetFireAt(v)
	})
}

// UpdateFireAt sets the "fire_at" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateFireAt() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateFireAt()
	})
}

// SetCallbackURL sets the "callback_url" field.
func (u *AgentCronFireUpsertBulk) SetCallbackURL(v string) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetCallbackURL(v)
	})
}

// UpdateCallbackURL sets the "callback_url" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateCallbackURL() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateCallbackURL()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *AgentCronFireUpsertBulk) SetDedupKey(v string) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateDedupKey() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateDedupKey()
	})
}

// SetScheduleID sets the "schedule_id" field.
func (u *AgentCronFireUpsertBulk) SetScheduleID(v string) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetScheduleID(v)
	})
}

// UpdateScheduleID sets the "schedule_id" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateScheduleID() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateScheduleID()
	})
}

// SetState sets the "state" field.
func (u *AgentCronFireUpsertBulk) SetState(v agentcronfire.State) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateState() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateState()
	})
}

// SetAttempts sets the "attempts" field.
func (u *AgentCronFireUpsertBulk) SetAttempts(v int) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *AgentCronFireUpsertBulk) AddAttempts(v int) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateAttempts() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *AgentCronFireUpsertBulk) SetLastError(v string) *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AgentCronFireUpsertBulk) UpdateLastError() *AgentCronFireUpsertBulk {
	return u.Update(func(s *AgentCronFireUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *AgentCronFireUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AgentCronFireCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AgentCronFireCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AgentCronFireUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
