// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/agentcronfire"
)

// AgentCronFire is the model entity for the AgentCronFire schema.
type AgentCronFire struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AgentRowID holds the value of the "agent_row_id" field.
	AgentRowID int64 `json:"agent_row_id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// FireAt holds the value of the "fire_at" field.
	FireAt time.Time `json:"fire_at,omitempty"`
	// CallbackURL holds the value of the "callback_url" field.
	CallbackURL string `json:"callback_url,omitempty"`
	// DedupKey holds the value of the "dedup_key" field.
	DedupKey string `json:"dedup_key,omitempty"`
	// ScheduleID holds the value of the "schedule_id" field.
	ScheduleID string `json:"schedule_id,omitempty"`
	// State holds the value of the "state" field.
	State agentcronfire.State `json:"state,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError    string `json:"last_error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentCronFire) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentcronfire.FieldID, agentcronfire.FieldAgentRowID, agentcronfire.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case agentcronfire.FieldJobID, agentcronfire.FieldCallbackURL, agentcronfire.FieldDedupKey, agentcronfire.FieldScheduleID, agentcronfire.FieldState, agentcronfire.FieldLastError:
			values[i] = new(sql.NullString)
		case agentcronfire.FieldCreatedAt, agentcronfire.FieldUpdatedAt, agentcronfire.FieldFireAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentCronFire fields.
func (_m *AgentCronFire) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentcronfire.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case agentcronfire.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentcronfire.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentcronfire.FieldAgentRowID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_row_id", values[i])
			} else if value.Valid {
				_m.AgentRowID = value.Int64
			}
		case agentcronfire.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case agentcronfire.FieldFireAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fire_at", values[i])
			} else if value.Valid {
				_m.FireAt = value.Time
			}
		case agentcronfire.FieldCallbackURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_url", values[i])
			} else if value.Valid {
				_m.CallbackURL = value.String
			}
		case agentcronfire.FieldDedupKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dedup_key", values[i])
			} else if value.Valid {
				_m.DedupKey = value.String
			}
		case agentcronfire.FieldScheduleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field schedule_id", values[i])
			} else if value.Valid {
				_m.ScheduleID = value.String
			}
		case agentcronfire.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = agentcronfire.State(value.String)
			}
		case agentcronfire.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case agentcronfire.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentCronFire.
// This includes values selected through modifiers, order, etc.
func (_m *AgentCronFire) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AgentCronFire.
// Note that you need to call AgentCronFire.Unwrap() before calling this method if this AgentCronFire
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentCronFire) Update() *AgentCronFireUpdateOne {
	return NewAgentCronFireClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentCronFire entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentCronFire) Unwrap() *AgentCronFire {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentCronFire is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentCronFire) String() string {
	var builder strings.Builder
	builder.WriteString("AgentCronFire(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("agent_row_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentRowID))
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("fire_at=")
	builder.WriteString(_m.FireAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("callback_url=")
	builder.WriteString(_m.CallbackURL)
	builder.WriteString(", ")
	builder.WriteString("dedup_key=")
	builder.WriteString(_m.DedupKey)
	builder.WriteString(", ")
	builder.WriteString("schedule_id=")
	builder.WriteString(_m.ScheduleID)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteByte(')')
	return builder.String()
}

// AgentCronFires is a parsable slice of AgentCronFire.
type AgentCronFires []*AgentCronFire
