// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/oauthdeviceauthorization"
)

// OAuthDeviceAuthorization is the model entity for the OAuthDeviceAuthorization schema.
type OAuthDeviceAuthorization struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeviceCode holds the value of the "device_code" field.
	DeviceCode string `json:"device_code,omitempty"`
	// UserCode holds the value of the "user_code" field.
	UserCode string `json:"user_code,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ApprovedUserID holds the value of the "approved_user_id" field.
	ApprovedUserID *int64 `json:"approved_user_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// LastPolledAt holds the value of the "last_polled_at" field.
	LastPolledAt *time.Time `json:"last_polled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthDeviceAuthorization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthdeviceauthorization.FieldID, oauthdeviceauthorization.FieldApprovedUserID:
			values[i] = new(sql.NullInt64)
		case oauthdeviceauthorization.FieldDeviceCode, oauthdeviceauthorization.FieldUserCode, oauthdeviceauthorization.FieldClientID, oauthdeviceauthorization.FieldScope, oauthdeviceauthorization.FieldStatus:
			values[i] = new(sql.NullString)
		case oauthdeviceauthorization.FieldCreatedAt, oauthdeviceauthorization.FieldUpdatedAt, oauthdeviceauthorization.FieldExpiresAt, oauthdeviceauthorization.FieldLastPolledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthDeviceAuthorization fields.
func (_m *OAuthDeviceAuthorization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthdeviceauthorization.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case oauthdeviceauthorization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthdeviceauthorization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case oauthdeviceauthorization.FieldDeviceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_code", values[i])
			} else if value.Valid {
				_m.DeviceCode = value.String
			}
		case oauthdeviceauthorization.FieldUserCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_code", values[i])
			} else if value.Valid {
				_m.UserCode = value.String
			}
		case oauthdeviceauthorization.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthdeviceauthorization.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case oauthdeviceauthorization.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case oauthdeviceauthorization.FieldApprovedUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_user_id", values[i])
			} else if value.Valid {
				_m.ApprovedUserID = new(int64)
				*_m.ApprovedUserID = value.Int64
			}
		case oauthdeviceauthorization.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthdeviceauthorization.FieldLastPolledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_polled_at", values[i])
			} else if value.Valid {
				_m.LastPolledAt = new(time.Time)
				*_m.LastPolledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthDeviceAuthorization.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthDeviceAuthorization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthDeviceAuthorization.
// Note that you need to call OAuthDeviceAuthorization.Unwrap() before calling this method if this OAuthDeviceAuthorization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthDeviceAuthorization) Update() *OAuthDeviceAuthorizationUpdateOne {
	return NewOAuthDeviceAuthorizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthDeviceAuthorization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthDeviceAuthorization) Unwrap() *OAuthDeviceAuthorization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthDeviceAuthorization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthDeviceAuthorization) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthDeviceAuthorization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("device_code=")
	builder.WriteString(_m.DeviceCode)
	builder.WriteString(", ")
	builder.WriteString("user_code=")
	builder.WriteString(_m.UserCode)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ApprovedUserID; v != nil {
		builder.WriteString("approved_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastPolledAt; v != nil {
		builder.WriteString("last_polled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthDeviceAuthorizations is a parsable slice of OAuthDeviceAuthorization.
type OAuthDeviceAuthorizations []*OAuthDeviceAuthorization
