// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthdeviceauthorization"
)

// OAuthDeviceAuthorizationCreate is the builder for creating a OAuthDeviceAuthorization entity.
type OAuthDeviceAuthorizationCreate struct {
	config
	mutation *OAuthDeviceAuthorizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthDeviceAuthorizationCreate) SetCreatedAt(v time.Time) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableCreatedAt(v *time.Time) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthDeviceAuthorizationCreate) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableUpdatedAt(v *time.Time) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeviceCode sets the "device_code" field.
func (_c *OAuthDeviceAuthorizationCreate) SetDeviceCode(v string) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetDeviceCode(v)
	return _c
}

// SetUserCode sets the "user_code" field.
func (_c *OAuthDeviceAuthorizationCreate) SetUserCode(v string) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetUserCode(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthDeviceAuthorizationCreate) SetClientID(v string) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *OAuthDeviceAuthorizationCreate) SetScope(v string) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableScope(v *string) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OAuthDeviceAuthorizationCreate) SetStatus(v string) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableStatus(v *string) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetApprovedUserID sets the "approved_user_id" field.
func (_c *OAuthDeviceAuthorizationCreate) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetApprovedUserID(v)
	return _c
}

// SetNillableApprovedUserID sets the "approved_user_id" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableApprovedUserID(v *int64) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetApprovedUserID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthDeviceAuthorizationCreate) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_c *OAuthDeviceAuthorizationCreate) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationCreate {
	_c.mutation.SetLastPolledAt(v)
	return _c
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_c *OAuthDeviceAuthorizationCreate) SetNillableLastPolledAt(v *time.Time) *OAuthDeviceAuthorizationCreate {
	if v != nil {
		_c.SetLastPolledAt(*v)
	}
	return _c
}

// Mutation returns the OAuthDeviceAuthorizationMutation object of the builder.
func (_c *OAuthDeviceAuthorizationCreate) Mutation() *OAuthDeviceAuthorizationMutation {
	return _c.mutation
}

// Save creates the OAuthDeviceAuthorization in the database.
func (_c *OAuthDeviceAuthorizationCreate) Save(ctx context.Context) (*OAuthDeviceAuthorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthDeviceAuthorizationCreate) SaveX(ctx context.Context) *OAuthDeviceAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthDeviceAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthDeviceAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthDeviceAuthorizationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthdeviceauthorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthdeviceauthorization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Scope(); !ok {
		v := oauthdeviceauthorization.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := oauthdeviceauthorization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthDeviceAuthorizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.updated_at"`)}
	}
	if _, ok := _c.mutation.DeviceCode(); !ok {
		return &ValidationError{Name: "device_code", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.device_code"`)}
	}
	if v, ok := _c.mutation.DeviceCode(); ok {
		if err := oauthdeviceauthorization.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.device_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserCode(); !ok {
		return &ValidationError{Name: "user_code", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.user_code"`)}
	}
	if v, ok := _c.mutation.UserCode(); ok {
		if err := oauthdeviceauthorization.UserCodeValidator(v); err != nil {
			return &ValidationError{Name: "user_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.user_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthdeviceauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := oauthdeviceauthorization.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := oauthdeviceauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthDeviceAuthorization.expires_at"`)}
	}
	return nil
}

func (_c *OAuthDeviceAuthorizationCreate) sqlSave(ctx context.Context) (*OAuthDeviceAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthDeviceAuthorizationCreate) createSpec() (*OAuthDeviceAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthDeviceAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthdeviceauthorization.Table, sqlgraph.NewFieldSpec(oauthdeviceauthorization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeviceCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldDeviceCode, field.TypeString, value)
		_node.DeviceCode = value
	}
	if value, ok := _c.mutation.UserCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUserCode, field.TypeString, value)
		_node.UserCode = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ApprovedUserID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64, value)
		_node.ApprovedUserID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastPolledAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldLastPolledAt, field.TypeTime, value)
		_node.LastPolledAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthDeviceAuthorization.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthDeviceAuthorizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthDeviceAuthorizationCreate) OnConflict(opts ...sql.ConflictOption) *OAuthDeviceAuthorizationUpsertOne {
	_c.conflict = opts
	return &OAuthDeviceAuthorizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthDeviceAuthorizationCreate) OnConflictColumns(columns ...string) *OAuthDeviceAuthorizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthDeviceAuthorizationUpsertOne{
		create: _c,
	}
}

type (
	// OAuthDeviceAuthorizationUpsertOne is the builder for "upsert"-ing
	//  one OAuthDeviceAuthorization node.
	OAuthDeviceAuthorizationUpsertOne struct {
		create *OAuthDeviceAuthorizationCreate
	}

	// OAuthDeviceAuthorizationUpsert is the "OnConflict" setter.
	OAuthDeviceAuthorizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceAuthorizationUpsert) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateUpdatedAt() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldUpdatedAt)
	return u
}

// SetDeviceCode sets the "device_code" field.
func (u *OAuthDeviceAuthorizationUpsert) SetDeviceCode(v string) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldDeviceCode, v)
	return u
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateDeviceCode() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldDeviceCode)
	return u
}

// SetUserCode sets the "user_code" field.
func (u *OAuthDeviceAuthorizationUpsert) SetUserCode(v string) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldUserCode, v)
	return u
}

// UpdateUserCode sets the "user_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateUserCode() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldUserCode)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceAuthorizationUpsert) SetClientID(v string) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateClientID() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldClientID)
	return u
}

// SetScope sets the "scope" field.
func (u *OAuthDeviceAuthorizationUpsert) SetScope(v string) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateScope() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldScope)
	return u
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceAuthorizationUpsert) SetStatus(v string) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateStatus() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldStatus)
	return u
}

// SetApprovedUserID sets the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsert) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldApprovedUserID, v)
	return u
}

// UpdateApprovedUserID sets the "approved_user_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateApprovedUserID() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldApprovedUserID)
	return u
}

// AddApprovedUserID adds v to the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsert) AddApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsert {
	u.Add(oauthdeviceauthorization.FieldApprovedUserID, v)
	return u
}

// ClearApprovedUserID clears the value of the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsert) ClearApprovedUserID() *OAuthDeviceAuthorizationUpsert {
	u.SetNull(oauthdeviceauthorization.FieldApprovedUserID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceAuthorizationUpsert) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateExpiresAt() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldExpiresAt)
	return u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsert) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationUpsert {
	u.Set(oauthdeviceauthorization.FieldLastPolledAt, v)
	return u
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsert) UpdateLastPolledAt() *OAuthDeviceAuthorizationUpsert {
	u.SetExcluded(oauthdeviceauthorization.FieldLastPolledAt)
	return u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsert) ClearLastPolledAt() *OAuthDeviceAuthorizationUpsert {
	u.SetNull(oauthdeviceauthorization.FieldLastPolledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateNewValues() *OAuthDeviceAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthdeviceauthorization.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthDeviceAuthorizationUpsertOne) Ignore() *OAuthDeviceAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthDeviceAuthorizationUpsertOne) DoNothing() *OAuthDeviceAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthDeviceAuthorizationCreate.OnConflict
// documentation for more info.
func (u *OAuthDeviceAuthorizationUpsertOne) Update(set func(*OAuthDeviceAuthorizationUpsert)) *OAuthDeviceAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthDeviceAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateUpdatedAt() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCode sets the "device_code" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetDeviceCode(v string) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetDeviceCode(v)
	})
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateDeviceCode() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateDeviceCode()
	})
}

// SetUserCode sets the "user_code" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetUserCode(v string) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetUserCode(v)
	})
}

// UpdateUserCode sets the "user_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateUserCode() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateUserCode()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetClientID(v string) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateClientID() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateClientID()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetScope(v string) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateScope() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateScope()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetStatus(v string) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateStatus() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateStatus()
	})
}

// SetApprovedUserID sets the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetApprovedUserID(v)
	})
}

// AddApprovedUserID adds v to the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertOne) AddApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.AddApprovedUserID(v)
	})
}

// UpdateApprovedUserID sets the "approved_user_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateApprovedUserID() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateApprovedUserID()
	})
}

// ClearApprovedUserID clears the value of the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertOne) ClearApprovedUserID() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.ClearApprovedUserID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateExpiresAt() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsertOne) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertOne) UpdateLastPolledAt() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsertOne) ClearLastPolledAt() *OAuthDeviceAuthorizationUpsertOne {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.ClearLastPolledAt()
	})
}

// Exec executes the query.
func (u *OAuthDeviceAuthorizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthDeviceAuthorizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthDeviceAuthorizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthDeviceAuthorizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthDeviceAuthorizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthDeviceAuthorizationCreateBulk is the builder for creating many OAuthDeviceAuthorization entities in bulk.
type OAuthDeviceAuthorizationCreateBulk struct {
	config
	err      error
	builders []*OAuthDeviceAuthorizationCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthDeviceAuthorization entities in the database.
func (_c *OAuthDeviceAuthorizationCreateBulk) Save(ctx context.Context) ([]*OAuthDeviceAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthDeviceAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthDeviceAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthDeviceAuthorizationCreateBulk) SaveX(ctx context.Context) []*OAuthDeviceAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthDeviceAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthDeviceAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthDeviceAuthorization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthDeviceAuthorizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthDeviceAuthorizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthDeviceAuthorizationUpsertBulk {
	_c.conflict = opts
	return &OAuthDeviceAuthorizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthDeviceAuthorizationCreateBulk) OnConflictColumns(columns ...string) *OAuthDeviceAuthorizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthDeviceAuthorizationUpsertBulk{
		create: _c,
	}
}

// OAuthDeviceAuthorizationUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthDeviceAuthorization nodes.
type OAuthDeviceAuthorizationUpsertBulk struct {
	create *OAuthDeviceAuthorizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateNewValues() *OAuthDeviceAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthdeviceauthorization.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthDeviceAuthorization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthDeviceAuthorizationUpsertBulk) Ignore() *OAuthDeviceAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthDeviceAuthorizationUpsertBulk) DoNothing() *OAuthDeviceAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthDeviceAuthorizationCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthDeviceAuthorizationUpsertBulk) Update(set func(*OAuthDeviceAuthorizationUpsert)) *OAuthDeviceAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthDeviceAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateUpdatedAt() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceCode sets the "device_code" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetDeviceCode(v string) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetDeviceCode(v)
	})
}

// UpdateDeviceCode sets the "device_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateDeviceCode() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateDeviceCode()
	})
}

// SetUserCode sets the "user_code" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetUserCode(v string) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetUserCode(v)
	})
}

// UpdateUserCode sets the "user_code" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateUserCode() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateUserCode()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetClientID(v string) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateClientID() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateClientID()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetScope(v string) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateScope() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateScope()
	})
}

// SetStatus sets the "status" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetStatus(v string) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateStatus() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateStatus()
	})
}

// SetApprovedUserID sets the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetApprovedUserID(v)
	})
}

// AddApprovedUserID adds v to the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) AddApprovedUserID(v int64) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.AddApprovedUserID(v)
	})
}

// UpdateApprovedUserID sets the "approved_user_id" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateApprovedUserID() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateApprovedUserID()
	})
}

// ClearApprovedUserID clears the value of the "approved_user_id" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) ClearApprovedUserID() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.ClearApprovedUserID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateExpiresAt() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastPolledAt sets the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.SetLastPolledAt(v)
	})
}

// UpdateLastPolledAt sets the "last_polled_at" field to the value that was provided on create.
func (u *OAuthDeviceAuthorizationUpsertBulk) UpdateLastPolledAt() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.UpdateLastPolledAt()
	})
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (u *OAuthDeviceAuthorizationUpsertBulk) ClearLastPolledAt() *OAuthDeviceAuthorizationUpsertBulk {
	return u.Update(func(s *OAuthDeviceAuthorizationUpsert) {
		s.ClearLastPolledAt()
	})
}

// Exec executes the query.
func (u *OAuthDeviceAuthorizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthDeviceAuthorizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthDeviceAuthorizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthDeviceAuthorizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
