// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthdeviceauthorization"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthDeviceAuthorizationUpdate is the builder for updating OAuthDeviceAuthorization entities.
type OAuthDeviceAuthorizationUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthDeviceAuthorizationMutation
}

// Where appends a list predicates to the OAuthDeviceAuthorizationUpdate builder.
func (_u *OAuthDeviceAuthorizationUpdate) Where(ps ...predicate.OAuthDeviceAuthorization) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceCode sets the "device_code" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetDeviceCode(v string) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetDeviceCode(v)
	return _u
}

// SetNillableDeviceCode sets the "device_code" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableDeviceCode(v *string) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetDeviceCode(*v)
	}
	return _u
}

// SetUserCode sets the "user_code" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetUserCode(v string) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetUserCode(v)
	return _u
}

// SetNillableUserCode sets the "user_code" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableUserCode(v *string) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetUserCode(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetClientID(v string) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableClientID(v *string) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetScope(v string) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableScope(v *string) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetStatus(v string) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableStatus(v *string) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedUserID sets the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.ResetApprovedUserID()
	_u.mutation.SetApprovedUserID(v)
	return _u
}

// SetNillableApprovedUserID sets the "approved_user_id" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableApprovedUserID(v *int64) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetApprovedUserID(*v)
	}
	return _u
}

// AddApprovedUserID adds value to the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdate) AddApprovedUserID(v int64) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.AddApprovedUserID(v)
	return _u
}

// ClearApprovedUserID clears the value of the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdate) ClearApprovedUserID() *OAuthDeviceAuthorizationUpdate {
	_u.mutation.ClearApprovedUserID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableExpiresAt(v *time.Time) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *OAuthDeviceAuthorizationUpdate) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationUpdate {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdate) SetNillableLastPolledAt(v *time.Time) *OAuthDeviceAuthorizationUpdate {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *OAuthDeviceAuthorizationUpdate) ClearLastPolledAt() *OAuthDeviceAuthorizationUpdate {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// Mutation returns the OAuthDeviceAuthorizationMutation object of the builder.
func (_u *OAuthDeviceAuthorizationUpdate) Mutation() *OAuthDeviceAuthorizationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthDeviceAuthorizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthDeviceAuthorizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthDeviceAuthorizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthDeviceAuthorizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthDeviceAuthorizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthdeviceauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthDeviceAuthorizationUpdate) check() error {
	if v, ok := _u.mutation.DeviceCode(); ok {
		if err := oauthdeviceauthorization.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.device_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserCode(); ok {
		if err := oauthdeviceauthorization.UserCodeValidator(v); err != nil {
			return &ValidationError{Name: "user_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.user_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthdeviceauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := oauthdeviceauthorization.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthdeviceauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthDeviceAuthorizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthdeviceauthorization.Table, oauthdeviceauthorization.Columns, sqlgraph.NewFieldSpec(oauthdeviceauthorization.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldDeviceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUserCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedUserID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedUserID(); ok {
		_spec.AddField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64, value)
	}
	if _u.mutation.ApprovedUserIDCleared() {
		_spec.ClearField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(oauthdeviceauthorization.FieldLastPolledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthdeviceauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthDeviceAuthorizationUpdateOne is the builder for updating a single OAuthDeviceAuthorization entity.
type OAuthDeviceAuthorizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthDeviceAuthorizationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetUpdatedAt(v time.Time) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceCode sets the "device_code" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetDeviceCode(v string) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetDeviceCode(v)
	return _u
}

// SetNillableDeviceCode sets the "device_code" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableDeviceCode(v *string) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetDeviceCode(*v)
	}
	return _u
}

// SetUserCode sets the "user_code" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetUserCode(v string) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetUserCode(v)
	return _u
}

// SetNillableUserCode sets the "user_code" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableUserCode(v *string) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetUserCode(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetClientID(v string) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableClientID(v *string) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetScope(v string) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableScope(v *string) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetStatus(v string) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableStatus(v *string) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedUserID sets the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetApprovedUserID(v int64) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.ResetApprovedUserID()
	_u.mutation.SetApprovedUserID(v)
	return _u
}

// SetNillableApprovedUserID sets the "approved_user_id" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableApprovedUserID(v *int64) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetApprovedUserID(*v)
	}
	return _u
}

// AddApprovedUserID adds value to the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) AddApprovedUserID(v int64) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.AddApprovedUserID(v)
	return _u
}

// ClearApprovedUserID clears the value of the "approved_user_id" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) ClearApprovedUserID() *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.ClearApprovedUserID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetExpiresAt(v time.Time) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastPolledAt sets the "last_polled_at" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetLastPolledAt(v time.Time) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.SetLastPolledAt(v)
	return _u
}

// SetNillableLastPolledAt sets the "last_polled_at" field if the given value is not nil.
func (_u *OAuthDeviceAuthorizationUpdateOne) SetNillableLastPolledAt(v *time.Time) *OAuthDeviceAuthorizationUpdateOne {
	if v != nil {
		_u.SetLastPolledAt(*v)
	}
	return _u
}

// ClearLastPolledAt clears the value of the "last_polled_at" field.
func (_u *OAuthDeviceAuthorizationUpdateOne) ClearLastPolledAt() *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.ClearLastPolledAt()
	return _u
}

// Mutation returns the OAuthDeviceAuthorizationMutation object of the builder.
func (_u *OAuthDeviceAuthorizationUpdateOne) Mutation() *OAuthDeviceAuthorizationMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthDeviceAuthorizationUpdate builder.
func (_u *OAuthDeviceAuthorizationUpdateOne) Where(ps ...predicate.OAuthDeviceAuthorization) *OAuthDeviceAuthorizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthDeviceAuthorizationUpdateOne) Select(field string, fields ...string) *OAuthDeviceAuthorizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthDeviceAuthorization entity.
func (_u *OAuthDeviceAuthorizationUpdateOne) Save(ctx context.Context) (*OAuthDeviceAuthorization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthDeviceAuthorizationUpdateOne) SaveX(ctx context.Context) *OAuthDeviceAuthorization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthDeviceAuthorizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthDeviceAuthorizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthDeviceAuthorizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthdeviceauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthDeviceAuthorizationUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceCode(); ok {
		if err := oauthdeviceauthorization.DeviceCodeValidator(v); err != nil {
			return &ValidationError{Name: "device_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.device_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserCode(); ok {
		if err := oauthdeviceauthorization.UserCodeValidator(v); err != nil {
			return &ValidationError{Name: "user_code", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.user_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthdeviceauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := oauthdeviceauthorization.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthdeviceauthorization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthDeviceAuthorization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthDeviceAuthorizationUpdateOne) sqlSave(ctx context.Context) (_node *OAuthDeviceAuthorization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthdeviceauthorization.Table, oauthdeviceauthorization.Columns, sqlgraph.NewFieldSpec(oauthdeviceauthorization.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthDeviceAuthorization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthdeviceauthorization.FieldID)
		for _, f := range fields {
			if !oauthdeviceauthorization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthdeviceauthorization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldDeviceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserCode(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldUserCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedUserID(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedApprovedUserID(); ok {
		_spec.AddField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64, value)
	}
	if _u.mutation.ApprovedUserIDCleared() {
		_spec.ClearField(oauthdeviceauthorization.FieldApprovedUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastPolledAt(); ok {
		_spec.SetField(oauthdeviceauthorization.FieldLastPolledAt, field.TypeTime, value)
	}
	if _u.mutation.LastPolledAtCleared() {
		_spec.ClearField(oauthdeviceauthorization.FieldLastPolledAt, field.TypeTime)
	}
	_node = &OAuthDeviceAuthorization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthdeviceauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
