// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthauthorizationcode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OAuthAuthorizationCodeUpdate is the builder for updating OAuthAuthorizationCode entities.
type OAuthAuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizationCodeMutation
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdate) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAuthorizationCodeUpdate) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *OAuthAuthorizationCodeUpdate) SetCode(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableCode(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetClientID(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableClientID(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdate) SetUserID(v int64) *OAuthAuthorizationCodeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableUserID(v *int64) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdate) AddUserID(v int64) *OAuthAuthorizationCodeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationCodeUpdate) SetRedirectURI(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableRedirectURI(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *OAuthAuthorizationCodeUpdate) SetScope(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableScope(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationCodeUpdate) SetCodeChallenge(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableCodeChallenge(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationCodeUpdate) SetCodeChallengeMethod(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthAuthorizationCodeUpdate) SetStatus(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableStatus(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedTokenFamily sets the "issued_token_family" field.
func (_u *OAuthAuthorizationCodeUpdate) SetIssuedTokenFamily(v string) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetIssuedTokenFamily(v)
	return _u
}

// SetNillableIssuedTokenFamily sets the "issued_token_family" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableIssuedTokenFamily(v *string) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetIssuedTokenFamily(*v)
	}
	return _u
}

// ClearIssuedTokenFamily clears the value of the "issued_token_family" field.
func (_u *OAuthAuthorizationCodeUpdate) ClearIssuedTokenFamily() *OAuthAuthorizationCodeUpdate {
	_u.mutation.ClearIssuedTokenFamily()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdate) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdate) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAuthorizationCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthauthorizationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := oauthauthorizationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := oauthauthorizationcode.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorizationcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthauthorizationcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthauthorizationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedTokenFamily(); ok {
		if err := oauthauthorizationcode.IssuedTokenFamilyValidator(v); err != nil {
			return &ValidationError{Name: "issued_token_family", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.issued_token_family": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthauthorizationcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedTokenFamily(); ok {
		_spec.SetField(oauthauthorizationcode.FieldIssuedTokenFamily, field.TypeString, value)
	}
	if _u.mutation.IssuedTokenFamilyCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldIssuedTokenFamily, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAuthorizationCodeUpdateOne is the builder for updating a single OAuthAuthorizationCode entity.
type OAuthAuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAuthorizationCodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetCode(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableCode(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetClientID(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableClientID(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetUserID(v int64) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableUserID(v *int64) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OAuthAuthorizationCodeUpdateOne) AddUserID(v int64) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetRedirectURI(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableRedirectURI(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetScope(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableScope(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetCodeChallenge(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableCodeChallenge(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetCodeChallengeMethod(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetStatus(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableStatus(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssuedTokenFamily sets the "issued_token_family" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetIssuedTokenFamily(v string) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetIssuedTokenFamily(v)
	return _u
}

// SetNillableIssuedTokenFamily sets the "issued_token_family" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableIssuedTokenFamily(v *string) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetIssuedTokenFamily(*v)
	}
	return _u
}

// ClearIssuedTokenFamily clears the value of the "issued_token_family" field.
func (_u *OAuthAuthorizationCodeUpdateOne) ClearIssuedTokenFamily() *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.ClearIssuedTokenFamily()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationCodeUpdateOne) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Mutation() *OAuthAuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAuthorizationCodeUpdate builder.
func (_u *OAuthAuthorizationCodeUpdateOne) Where(ps ...predicate.OAuthAuthorizationCode) *OAuthAuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAuthorizationCodeUpdateOne) Select(field string, fields ...string) *OAuthAuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAuthorizationCode entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Save(ctx context.Context) (*OAuthAuthorizationCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) SaveX(ctx context.Context) *OAuthAuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthAuthorizationCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthauthorizationcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := oauthauthorizationcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorizationcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := oauthauthorizationcode.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorizationcode.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallengeMethod(); ok {
		if err := oauthauthorizationcode.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.code_challenge_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthauthorizationcode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IssuedTokenFamily(); ok {
		if err := oauthauthorizationcode.IssuedTokenFamilyValidator(v); err != nil {
			return &ValidationError{Name: "issued_token_family", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.issued_token_family": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAuthorizationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorizationcode.Table, oauthauthorizationcode.Columns, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthAuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorizationcode.FieldID)
		for _, f := range fields {
			if !oauthauthorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthauthorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(oauthauthorizationcode.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthauthorizationcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedTokenFamily(); ok {
		_spec.SetField(oauthauthorizationcode.FieldIssuedTokenFamily, field.TypeString, value)
	}
	if _u.mutation.IssuedTokenFamilyCleared() {
		_spec.ClearField(oauthauthorizationcode.FieldIssuedTokenFamily, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &OAuthAuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
