// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/org"
)

// OrgCreate is the builder for creating a Org entity.
type OrgCreate struct {
	config
	mutation *OrgMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgCreate) SetCreatedAt(v time.Time) *OrgCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgCreate) SetNillableCreatedAt(v *time.Time) *OrgCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgCreate) SetUpdatedAt(v time.Time) *OrgCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgCreate) SetNillableUpdatedAt(v *time.Time) *OrgCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *OrgCreate) SetSlug(v string) *OrgCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OrgCreate) SetName(v string) *OrgCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsPersonal sets the "is_personal" field.
func (_c *OrgCreate) SetIsPersonal(v bool) *OrgCreate {
	_c.mutation.SetIsPersonal(v)
	return _c
}

// SetNillableIsPersonal sets the "is_personal" field if the given value is not nil.
func (_c *OrgCreate) SetNillableIsPersonal(v *bool) *OrgCreate {
	if v != nil {
		_c.SetIsPersonal(*v)
	}
	return _c
}

// SetPersonalUserID sets the "personal_user_id" field.
func (_c *OrgCreate) SetPersonalUserID(v int64) *OrgCreate {
	_c.mutation.SetPersonalUserID(v)
	return _c
}

// SetNillablePersonalUserID sets the "personal_user_id" field if the given value is not nil.
func (_c *OrgCreate) SetNillablePersonalUserID(v *int64) *OrgCreate {
	if v != nil {
		_c.SetPersonalUserID(*v)
	}
	return _c
}

// Mutation returns the OrgMutation object of the builder.
func (_c *OrgCreate) Mutation() *OrgMutation {
	return _c.mutation
}

// Save creates the Org in the database.
func (_c *OrgCreate) Save(ctx context.Context) (*Org, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgCreate) SaveX(ctx context.Context) *Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := org.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := org.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsPersonal(); !ok {
		v := org.DefaultIsPersonal
		_c.mutation.SetIsPersonal(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Org.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Org.updated_at"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Org.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := org.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Org.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Org.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := org.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Org.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPersonal(); !ok {
		return &ValidationError{Name: "is_personal", err: errors.New(`ent: missing required field "Org.is_personal"`)}
	}
	return nil
}

func (_c *OrgCreate) sqlSave(ctx context.Context) (*Org, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgCreate) createSpec() (*Org, *sqlgraph.CreateSpec) {
	var (
		_node = &Org{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(org.Table, sqlgraph.NewFieldSpec(org.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(org.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(org.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(org.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(org.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsPersonal(); ok {
		_spec.SetField(org.FieldIsPersonal, field.TypeBool, value)
		_node.IsPersonal = value
	}
	if value, ok := _c.mutation.PersonalUserID(); ok {
		_spec.SetField(org.FieldPersonalUserID, field.TypeInt64, value)
		_node.PersonalUserID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Org.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgCreate) OnConflict(opts ...sql.ConflictOption) *OrgUpsertOne {
	_c.conflict = opts
	return &OrgUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgCreate) OnConflictColumns(columns ...string) *OrgUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUpsertOne{
		create: _c,
	}
}

type (
	// OrgUpsertOne is the builder for "upsert"-ing
	//  one Org node.
	OrgUpsertOne struct {
		create *OrgCreate
	}

	// OrgUpsert is the "OnConflict" setter.
	OrgUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUpsert) SetUpdatedAt(v time.Time) *OrgUpsert {
	u.Set(org.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUpsert) UpdateUpdatedAt() *OrgUpsert {
	u.SetExcluded(org.FieldUpdatedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *OrgUpsert) SetSlug(v string) *OrgUpsert {
	u.Set(org.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrgUpsert) UpdateSlug() *OrgUpsert {
	u.SetExcluded(org.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *OrgUpsert) SetName(v string) *OrgUpsert {
	u.Set(org.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUpsert) UpdateName() *OrgUpsert {
	u.SetExcluded(org.FieldName)
	return u
}

// SetIsPersonal sets the "is_personal" field.
func (u *OrgUpsert) SetIsPersonal(v bool) *OrgUpsert {
	u.Set(org.FieldIsPersonal, v)
	return u
}

// UpdateIsPersonal sets the "is_personal" field to the value that was provided on create.
func (u *OrgUpsert) UpdateIsPersonal() *OrgUpsert {
	u.SetExcluded(org.FieldIsPersonal)
	return u
}

// SetPersonalUserID sets the "personal_user_id" field.
func (u *OrgUpsert) SetPersonalUserID(v int64) *OrgUpsert {
	u.Set(org.FieldPersonalUserID, v)
	return u
}

// UpdatePersonalUserID sets the "personal_user_id" field to the value that was provided on create.
func (u *OrgUpsert) UpdatePersonalUserID() *OrgUpsert {
	u.SetExcluded(org.FieldPersonalUserID)
	return u
}

// AddPersonalUserID adds v to the "personal_user_id" field.
func (u *OrgUpsert) AddPersonalUserID(v int64) *OrgUpsert {
	u.Add(org.FieldPersonalUserID, v)
	return u
}

// ClearPersonalUserID clears the value of the "personal_user_id" field.
func (u *OrgUpsert) ClearPersonalUserID() *OrgUpsert {
	u.SetNull(org.FieldPersonalUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgUpsertOne) UpdateNewValues() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(org.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgUpsertOne) Ignore() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUpsertOne) DoNothing() *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgCreate.OnConflict
// documentation for more info.
func (u *OrgUpsertOne) Update(set func(*OrgUpsert)) *OrgUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUpsertOne) SetUpdatedAt(v time.Time) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateUpdatedAt() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *OrgUpsertOne) SetSlug(v string) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateSlug() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *OrgUpsertOne) SetName(v string) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateName() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateName()
	})
}

// SetIsPersonal sets the "is_personal" field.
func (u *OrgUpsertOne) SetIsPersonal(v bool) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetIsPersonal(v)
	})
}

// UpdateIsPersonal sets the "is_personal" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdateIsPersonal() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateIsPersonal()
	})
}

// SetPersonalUserID sets the "personal_user_id" field.
func (u *OrgUpsertOne) SetPersonalUserID(v int64) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.SetPersonalUserID(v)
	})
}

// AddPersonalUserID adds v to the "personal_user_id" field.
func (u *OrgUpsertOne) AddPersonalUserID(v int64) *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.AddPersonalUserID(v)
	})
}

// UpdatePersonalUserID sets the "personal_user_id" field to the value that was provided on create.
func (u *OrgUpsertOne) UpdatePersonalUserID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.UpdatePersonalUserID()
	})
}

// ClearPersonalUserID clears the value of the "personal_user_id" field.
func (u *OrgUpsertOne) ClearPersonalUserID() *OrgUpsertOne {
	return u.Update(func(s *OrgUpsert) {
		s.ClearPersonalUserID()
	})
}

// Exec executes the query.
func (u *OrgUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgCreateBulk is the builder for creating many Org entities in bulk.
type OrgCreateBulk struct {
	config
	err      error
	builders []*OrgCreate
	conflict []sql.ConflictOption
}

// Save creates the Org entities in the database.
func (_c *OrgCreateBulk) Save(ctx context.Context) ([]*Org, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Org, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgCreateBulk) SaveX(ctx context.Context) []*Org {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Org.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgUpsertBulk {
	_c.conflict = opts
	return &OrgUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgCreateBulk) OnConflictColumns(columns ...string) *OrgUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgUpsertBulk{
		create: _c,
	}
}

// OrgUpsertBulk is the builder for "upsert"-ing
// a bulk of Org nodes.
type OrgUpsertBulk struct {
	create *OrgCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgUpsertBulk) UpdateNewValues() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(org.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Org.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgUpsertBulk) Ignore() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgUpsertBulk) DoNothing() *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgCreateBulk.OnConflict
// documentation for more info.
func (u *OrgUpsertBulk) Update(set func(*OrgUpsert)) *OrgUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgUpsertBulk) SetUpdatedAt(v time.Time) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateUpdatedAt() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *OrgUpsertBulk) SetSlug(v string) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateSlug() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *OrgUpsertBulk) SetName(v string) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateName() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateName()
	})
}

// SetIsPersonal sets the "is_personal" field.
func (u *OrgUpsertBulk) SetIsPersonal(v bool) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetIsPersonal(v)
	})
}

// UpdateIsPersonal sets the "is_personal" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdateIsPersonal() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdateIsPersonal()
	})
}

// SetPersonalUserID sets the "personal_user_id" field.
func (u *OrgUpsertBulk) SetPersonalUserID(v int64) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.SetPersonalUserID(v)
	})
}

// AddPersonalUserID adds v to the "personal_user_id" field.
func (u *OrgUpsertBulk) AddPersonalUserID(v int64) *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.AddPersonalUserID(v)
	})
}

// UpdatePersonalUserID sets the "personal_user_id" field to the value that was provided on create.
func (u *OrgUpsertBulk) UpdatePersonalUserID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.UpdatePersonalUserID()
	})
}

// ClearPersonalUserID clears the value of the "personal_user_id" field.
func (u *OrgUpsertBulk) ClearPersonalUserID() *OrgUpsertBulk {
	return u.Update(func(s *OrgUpsert) {
		s.ClearPersonalUserID()
	})
}

// Exec executes the query.
func (u *OrgUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
