// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/orgmember"
)

// OrgMemberCreate is the builder for creating a OrgMember entity.
type OrgMemberCreate struct {
	config
	mutation *OrgMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgMemberCreate) SetCreatedAt(v time.Time) *OrgMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgMemberCreate) SetNillableCreatedAt(v *time.Time) *OrgMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgMemberCreate) SetUpdatedAt(v time.Time) *OrgMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgMemberCreate) SetNillableUpdatedAt(v *time.Time) *OrgMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *OrgMemberCreate) SetOrgID(v int64) *OrgMemberCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrgMemberCreate) SetUserID(v int64) *OrgMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *OrgMemberCreate) SetRole(v string) *OrgMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *OrgMemberCreate) SetNillableRole(v *string) *OrgMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// Mutation returns the OrgMemberMutation object of the builder.
func (_c *OrgMemberCreate) Mutation() *OrgMemberMutation {
	return _c.mutation
}

// Save creates the OrgMember in the database.
func (_c *OrgMemberCreate) Save(ctx context.Context) (*OrgMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgMemberCreate) SaveX(ctx context.Context) *OrgMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := orgmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := orgmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := orgmember.DefaultRole
		_c.mutation.SetRole(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrgMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrgMember.updated_at"`)}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "OrgMember.org_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrgMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OrgMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := orgmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrgMember.role": %w`, err)}
		}
	}
	return nil
}

func (_c *OrgMemberCreate) sqlSave(ctx context.Context) (*OrgMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgMemberCreate) createSpec() (*OrgMember, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orgmember.Table, sqlgraph.NewFieldSpec(orgmember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orgmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orgmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(orgmember.FieldOrgID, field.TypeInt64, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(orgmember.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(orgmember.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgMemberCreate) OnConflict(opts ...sql.ConflictOption) *OrgMemberUpsertOne {
	_c.conflict = opts
	return &OrgMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgMemberCreate) OnConflictColumns(columns ...string) *OrgMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgMemberUpsertOne{
		create: _c,
	}
}

type (
	// OrgMemberUpsertOne is the builder for "upsert"-ing
	//  one OrgMember node.
	OrgMemberUpsertOne struct {
		create *OrgMemberCreate
	}

	// OrgMemberUpsert is the "OnConflict" setter.
	OrgMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgMemberUpsert) SetUpdatedAt(v time.Time) *OrgMemberUpsert {
	u.Set(orgmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgMemberUpsert) UpdateUpdatedAt() *OrgMemberUpsert {
	u.SetExcluded(orgmember.FieldUpdatedAt)
	return u
}

// SetOrgID sets the "org_id" field.
func (u *OrgMemberUpsert) SetOrgID(v int64) *OrgMemberUpsert {
	u.Set(orgmember.FieldOrgID, v)
	return u
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgMemberUpsert) UpdateOrgID() *OrgMemberUpsert {
	u.SetExcluded(orgmember.FieldOrgID)
	return u
}

// AddOrgID adds v to the "org_id" field.
func (u *OrgMemberUpsert) AddOrgID(v int64) *OrgMemberUpsert {
	u.Add(orgmember.FieldOrgID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrgMemberUpsert) SetUserID(v int64) *OrgMemberUpsert {
	u.Set(orgmember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrgMemberUpsert) UpdateUserID() *OrgMemberUpsert {
	u.SetExcluded(orgmember.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OrgMemberUpsert) AddUserID(v int64) *OrgMemberUpsert {
	u.Add(orgmember.FieldUserID, v)
	return u
}

// SetRole sets the "role" field.
func (u *OrgMemberUpsert) SetRole(v string) *OrgMemberUpsert {
	u.Set(orgmember.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OrgMemberUpsert) UpdateRole() *OrgMemberUpsert {
	u.SetExcluded(orgmember.FieldRole)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgMemberUpsertOne) UpdateNewValues() *OrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(orgmember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgMemberUpsertOne) Ignore() *OrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgMemberUpsertOne) DoNothing() *OrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgMemberCreate.OnConflict
// documentation for more info.
func (u *OrgMemberUpsertOne) Update(set func(*OrgMemberUpsert)) *OrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgMemberUpsertOne) SetUpdatedAt(v time.Time) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgMemberUpsertOne) UpdateUpdatedAt() *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgMemberUpsertOne) SetOrgID(v int64) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetOrgID(v)
	})
}

// AddOrgID adds v to the "org_id" field.
func (u *OrgMemberUpsertOne) AddOrgID(v int64) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.AddOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgMemberUpsertOne) UpdateOrgID() *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateOrgID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrgMemberUpsertOne) SetUserID(v int64) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrgMemberUpsertOne) AddUserID(v int64) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrgMemberUpsertOne) UpdateUserID() *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *OrgMemberUpsertOne) SetRole(v string) *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OrgMemberUpsertOne) UpdateRole() *OrgMemberUpsertOne {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *OrgMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgMemberCreateBulk is the builder for creating many OrgMember entities in bulk.
type OrgMemberCreateBulk struct {
	config
	err      error
	builders []*OrgMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the OrgMember entities in the database.
func (_c *OrgMemberCreateBulk) Save(ctx context.Context) ([]*OrgMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrgMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgMemberCreateBulk) SaveX(ctx context.Context) []*OrgMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgMemberUpsertBulk {
	_c.conflict = opts
	return &OrgMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgMemberCreateBulk) OnConflictColumns(columns ...string) *OrgMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgMemberUpsertBulk{
		create: _c,
	}
}

// OrgMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of OrgMember nodes.
type OrgMemberUpsertBulk struct {
	create *OrgMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgMemberUpsertBulk) UpdateNewValues() *OrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(orgmember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgMemberUpsertBulk) Ignore() *OrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgMemberUpsertBulk) DoNothing() *OrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgMemberCreateBulk.OnConflict
// documentation for more info.
func (u *OrgMemberUpsertBulk) Update(set func(*OrgMemberUpsert)) *OrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgMemberUpsertBulk) SetUpdatedAt(v time.Time) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgMemberUpsertBulk) UpdateUpdatedAt() *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgMemberUpsertBulk) SetOrgID(v int64) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetOrgID(v)
	})
}

// AddOrgID adds v to the "org_id" field.
func (u *OrgMemberUpsertBulk) AddOrgID(v int64) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.AddOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgMemberUpsertBulk) UpdateOrgID() *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateOrgID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrgMemberUpsertBulk) SetUserID(v int64) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrgMemberUpsertBulk) AddUserID(v int64) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrgMemberUpsertBulk) UpdateUserID() *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *OrgMemberUpsertBulk) SetRole(v string) *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OrgMemberUpsertBulk) UpdateRole() *OrgMemberUpsertBulk {
	return u.Update(func(s *OrgMemberUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *OrgMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
