// Code generated by ent, DO NOT EDIT.

package oauthdeviceauthorization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeviceCode applies equality check predicate on the "device_code" field. It's identical to DeviceCodeEQ.
func DeviceCode(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldDeviceCode, v))
}

// UserCode applies equality check predicate on the "user_code" field. It's identical to UserCodeEQ.
func UserCode(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldUserCode, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldClientID, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldScope, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldStatus, v))
}

// ApprovedUserID applies equality check predicate on the "approved_user_id" field. It's identical to ApprovedUserIDEQ.
func ApprovedUserID(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldApprovedUserID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldExpiresAt, v))
}

// LastPolledAt applies equality check predicate on the "last_polled_at" field. It's identical to LastPolledAtEQ.
func LastPolledAt(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldLastPolledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeviceCodeEQ applies the EQ predicate on the "device_code" field.
func DeviceCodeEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldDeviceCode, v))
}

// DeviceCodeNEQ applies the NEQ predicate on the "device_code" field.
func DeviceCodeNEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldDeviceCode, v))
}

// DeviceCodeIn applies the In predicate on the "device_code" field.
func DeviceCodeIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldDeviceCode, vs...))
}

// DeviceCodeNotIn applies the NotIn predicate on the "device_code" field.
func DeviceCodeNotIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldDeviceCode, vs...))
}

// DeviceCodeGT applies the GT predicate on the "device_code" field.
func DeviceCodeGT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldDeviceCode, v))
}

// DeviceCodeGTE applies the GTE predicate on the "device_code" field.
func DeviceCodeGTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldDeviceCode, v))
}

// DeviceCodeLT applies the LT predicate on the "device_code" field.
func DeviceCodeLT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldDeviceCode, v))
}

// DeviceCodeLTE applies the LTE predicate on the "device_code" field.
func DeviceCodeLTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldDeviceCode, v))
}

// DeviceCodeContains applies the Contains predicate on the "device_code" field.
func DeviceCodeContains(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContains(FieldDeviceCode, v))
}

// DeviceCodeHasPrefix applies the HasPrefix predicate on the "device_code" field.
func DeviceCodeHasPrefix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasPrefix(FieldDeviceCode, v))
}

// DeviceCodeHasSuffix applies the HasSuffix predicate on the "device_code" field.
func DeviceCodeHasSuffix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasSuffix(FieldDeviceCode, v))
}

// DeviceCodeEqualFold applies the EqualFold predicate on the "device_code" field.
func DeviceCodeEqualFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEqualFold(FieldDeviceCode, v))
}

// DeviceCodeContainsFold applies the ContainsFold predicate on the "device_code" field.
func DeviceCodeContainsFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContainsFold(FieldDeviceCode, v))
}

// UserCodeEQ applies the EQ predicate on the "user_code" field.
func UserCodeEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldUserCode, v))
}

// UserCodeNEQ applies the NEQ predicate on the "user_code" field.
func UserCodeNEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldUserCode, v))
}

// UserCodeIn applies the In predicate on the "user_code" field.
func UserCodeIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldUserCode, vs...))
}

// UserCodeNotIn applies the NotIn predicate on the "user_code" field.
func UserCodeNotIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldUserCode, vs...))
}

// UserCodeGT applies the GT predicate on the "user_code" field.
func UserCodeGT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldUserCode, v))
}

// UserCodeGTE applies the GTE predicate on the "user_code" field.
func UserCodeGTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldUserCode, v))
}

// UserCodeLT applies the LT predicate on the "user_code" field.
func UserCodeLT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldUserCode, v))
}

// UserCodeLTE applies the LTE predicate on the "user_code" field.
func UserCodeLTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldUserCode, v))
}

// UserCodeContains applies the Contains predicate on the "user_code" field.
func UserCodeContains(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContains(FieldUserCode, v))
}

// UserCodeHasPrefix applies the HasPrefix predicate on the "user_code" field.
func UserCodeHasPrefix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasPrefix(FieldUserCode, v))
}

// UserCodeHasSuffix applies the HasSuffix predicate on the "user_code" field.
func UserCodeHasSuffix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasSuffix(FieldUserCode, v))
}

// UserCodeEqualFold applies the EqualFold predicate on the "user_code" field.
func UserCodeEqualFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEqualFold(FieldUserCode, v))
}

// UserCodeContainsFold applies the ContainsFold predicate on the "user_code" field.
func UserCodeContainsFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContainsFold(FieldUserCode, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContainsFold(FieldClientID, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContainsFold(FieldScope, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldContainsFold(FieldStatus, v))
}

// ApprovedUserIDEQ applies the EQ predicate on the "approved_user_id" field.
func ApprovedUserIDEQ(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldApprovedUserID, v))
}

// ApprovedUserIDNEQ applies the NEQ predicate on the "approved_user_id" field.
func ApprovedUserIDNEQ(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldApprovedUserID, v))
}

// ApprovedUserIDIn applies the In predicate on the "approved_user_id" field.
func ApprovedUserIDIn(vs ...int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldApprovedUserID, vs...))
}

// ApprovedUserIDNotIn applies the NotIn predicate on the "approved_user_id" field.
func ApprovedUserIDNotIn(vs ...int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldApprovedUserID, vs...))
}

// ApprovedUserIDGT applies the GT predicate on the "approved_user_id" field.
func ApprovedUserIDGT(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldApprovedUserID, v))
}

// ApprovedUserIDGTE applies the GTE predicate on the "approved_user_id" field.
func ApprovedUserIDGTE(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldApprovedUserID, v))
}

// ApprovedUserIDLT applies the LT predicate on the "approved_user_id" field.
func ApprovedUserIDLT(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldApprovedUserID, v))
}

// ApprovedUserIDLTE applies the LTE predicate on the "approved_user_id" field.
func ApprovedUserIDLTE(v int64) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldApprovedUserID, v))
}

// ApprovedUserIDIsNil applies the IsNil predicate on the "approved_user_id" field.
func ApprovedUserIDIsNil() predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIsNull(FieldApprovedUserID))
}

// ApprovedUserIDNotNil applies the NotNil predicate on the "approved_user_id" field.
func ApprovedUserIDNotNil() predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotNull(FieldApprovedUserID))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldExpiresAt, v))
}

// LastPolledAtEQ applies the EQ predicate on the "last_polled_at" field.
func LastPolledAtEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldEQ(FieldLastPolledAt, v))
}

// LastPolledAtNEQ applies the NEQ predicate on the "last_polled_at" field.
func LastPolledAtNEQ(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNEQ(FieldLastPolledAt, v))
}

// LastPolledAtIn applies the In predicate on the "last_polled_at" field.
func LastPolledAtIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIn(FieldLastPolledAt, vs...))
}

// LastPolledAtNotIn applies the NotIn predicate on the "last_polled_at" field.
func LastPolledAtNotIn(vs ...time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotIn(FieldLastPolledAt, vs...))
}

// LastPolledAtGT applies the GT predicate on the "last_polled_at" field.
func LastPolledAtGT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGT(FieldLastPolledAt, v))
}

// LastPolledAtGTE applies the GTE predicate on the "last_polled_at" field.
func LastPolledAtGTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldGTE(FieldLastPolledAt, v))
}

// LastPolledAtLT applies the LT predicate on the "last_polled_at" field.
func LastPolledAtLT(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLT(FieldLastPolledAt, v))
}

// LastPolledAtLTE applies the LTE predicate on the "last_polled_at" field.
func LastPolledAtLTE(v time.Time) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldLTE(FieldLastPolledAt, v))
}

// LastPolledAtIsNil applies the IsNil predicate on the "last_polled_at" field.
func LastPolledAtIsNil() predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldIsNull(FieldLastPolledAt))
}

// LastPolledAtNotNil applies the NotNil predicate on the "last_polled_at" field.
func LastPolledAtNotNil() predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.FieldNotNull(FieldLastPolledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthDeviceAuthorization) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthDeviceAuthorization) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthDeviceAuthorization) predicate.OAuthDeviceAuthorization {
	return predicate.OAuthDeviceAuthorization(sql.NotPredicates(p))
}
